### ISSUE TITLE
ConnectionError (Error 417) for historical data

### ISSUE THREAD

**Issue by kostja1979** [Mael-J/mstarpy#3]
Hi,

since two weeks I am facing with the following error when I try to get the historical data for any fund or stock. The same code worked fine before this issue.

```
Traceback (most recent call last):
  File "***\ex_MS.py", line 20, in <module>
    history = fund.nav(start_date=start_date, end_date=end_date, frequency="daily")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Lib\site-packages\mstarpy\funds.py", line 896, in nav
    return self.TimeSeries(["nav","totalReturn"],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Lib\site-packages\mstarpy\security.py", line 290, in TimeSeries
    not_200_response(url,response)
  File "***\Lib\site-packages\mstarpy\error.py", line 10, in not_200_response
    raise ConnectionError(f"Error {response.status_code} for the api {url}. Message : {response.reason}.")
ConnectionError: Error 417 for the api https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries?query=FOUSA00LIX:nav,totalReturn&frequency=d&startDate=2018-01-01&endDate=2023-12-19&trackMarketData=3.6.3&instid=MSERP. Message : Unknown.
```

Here an example:

```
fund = Funds(term="FOUSA00LIX", country="us")
print(fund.name)
start_date = datetime.date(2018, 1, 1)
end_date = datetime.date.today()
history = fund.nav(start_date=start_date, end_date=end_date, frequency="daily")
df_history = pd.DataFrame(history)
```

Thanks for your help and regards

**Comment by Mael-J** [comment]
Hello,

I found the error. It seems that Morningstar changed the payload instid=MSERP by instid=DOTCOM in the request


https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries?query=FOUSA00LIX:nav,totalReturn&frequency=d&startDate=2018-01-01&endDate=2023-12-19&trackMarketData=3.6.3&instid=MSERP

I modified the package. You will find the correction on GitHub or in the version 1.0.3 in pypi.org


Thank you.


Maël

________________________________
From: kostja1979 ***@***.***>
Sent: Tuesday, December 19, 2023 9:57:56 pm
To: Mael-J/mstarpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Mael-J/mstarpy] ConnectionError (Error 417) for historical data (Issue #3)


Hi,

since two weeks I am facing with the following error when I try to get the historical data for any fund or stock. The same code worked fine before this issue.

Traceback (most recent call last):
  File "***\ex_MS.py", line 20, in <module>
    history = fund.nav(start_date=start_date, end_date=end_date, frequency="daily")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Lib\site-packages\mstarpy\funds.py", line 896, in nav
    return self.TimeSeries(["nav","totalReturn"],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Lib\site-packages\mstarpy\security.py", line 290, in TimeSeries
    not_200_response(url,response)
  File "***\Lib\site-packages\mstarpy\error.py", line 10, in not_200_response
    raise ConnectionError(f"Error {response.status_code} for the api {url}. Message : {response.reason}.")
ConnectionError: Error 417 for the api https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries?query=FOUSA00LIX:nav,totalReturn&frequency=d&startDate=2018-01-01&endDate=2023-12-19&trackMarketData=3.6.3&instid=MSERP. Message : Unknown.


Here an example:

fund = Funds(term="FOUSA00LIX", country="us")
print(fund.name)
start_date = datetime.date(2018, 1, 1)
end_date = datetime.date.today()
history = fund.nav(start_date=start_date, end_date=end_date, frequency="daily")
df_history = pd.DataFrame(history)


Thanks for your help and regards

**Comment by kostja1979** [comment]
Thank you, now it works fine!
